# Generated by Django 5.1.3 on 2024-11-14 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatars.photo'),
        ),
    ]
