# Generated by Django 5.1.3 on 2024-11-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0002_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scene_data',
            field=models.JSONField(null=True),
        ),
    ]
